version: '3.8'

services:
  bocacheia_db:
    container_name: bocacheia_pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: bocacheia-pg
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
